# -*- coding: utf-8 -*-
# Hal ürünü adı (JSON'daki orijinal "ad" alanı) -> Wikimedia Commons arama terimi
# Bilimsel adlar kullanılıyor, Commons kategori sistemiyle daha isabetli eşleşir.

CEVIRI = {
    "Acur": "Cucumis melo flexuosus.jpg",
    "Adaçayi (yaş-taze)": "Salvia officinalis",
    "Ahududu(frambuaz)": "Rubus idaeus raspberry",
    "Alabaş(kohlrabi̇)": "Brassica oleracea gongylodes kohlrabi",
    "Ananas": "Ananas comosus fruit",
    "Armut": "Pyrus communis pear",
    "Asma Yapraği": "Vitis vinifera leaf",
    "Avokado": "Persea americana avocado",
    "Ayva": "Cydonia oblonga quince",
    "Bakla taze": "Vicia faba pods",
    "Balkabaği": "Cucurbita moschata pumpkin",
    "Bamya taze": "Abelmoschus esculentus okra",
    "Barbunya taze": "Phaseolus vulgaris cranberry bean pod",
    "Beyaz Lahana": "Brassica oleracea white cabbage",
    "Bezelye taze": "Pisum sativum green pea pod",
    "Bi̇ber Çarli̇ston": "Capsicum annuum charleston pepper",
    "Bi̇ber Dolmalik": "Capsicum annuum bell pepper",
    "Bi̇ber Salçalik (kapya)": "Capsicum annuum red pepper elongated",
    "Bi̇ber Si̇vri̇": "Capsicum annuum long green pepper",
    "Bi̇beri̇ye": "Rosmarinus officinalis rosemary",
    "Böğürtlen": "Rubus fruticosus blackberry",
    "Börülce taze": "Vigna unguiculata black eyed pea pod",
    "Brokoli̇": "Brassica oleracea broccoli",
    "Ci̇bes": "Prunus cerasifera fruit",
    "Çi̇lek": "Fragaria ananassa strawberry",
    "Deni̇z Börülcesi̇(deni̇z Otu Ege Otu)": "Salicornia samphire",
    "Dereotu (yaş-taze)": "Anethum graveolens dill",
    "Domates": "Solanum lycopersicum tomato",
    "Domates Salçalik": "Solanum lycopersicum roma tomato",
    "Dut": "Morus mulberry",
    "Ebegümeci̇": "Malva sylvestris",
    "Elma": "Malus domestica apple",
    "Elma Golden": "Malus domestica golden delicious apple",
    "Elma Granny Smith": "Malus domestica granny smith apple",
    "Elma Starking": "Malus domestica red delicious apple",
    "Engi̇nar": "Cynara scolymus artichoke",
    "Eri̇k": "Prunus domestica plum",
    "Fasulye taze": "Phaseolus vulgaris green bean pod",
    "Fesleğen(reyhan)": "Ocimum basilicum basil",
    "Greyfurt": "Citrus paradisi grapefruit",
    "Hardal Otu (yaş-taze)": "Brassica juncea mustard greens",
    "Havuç": "Daucus carota carrot",
    "Hi̇ndi̇ba (çi̇kori̇)": "Cichorium intybus chicory",
    "Hi̇ndi̇ba Endi̇vyen": "Cichorium endivia endive",
    "Hi̇ndi̇ba Radi̇ka": "Cichorium intybus radicchio",
    "Hi̇ndi̇stan Cevi̇zi̇": "Cocos nucifera coconut",
    "Isirgan (yaş-taze)": "Urtica dioica nettle",
    "Ispanak": "Spinach leaves pot without stems",
    "İnci̇r": "Ficus carica fig fruit",
    "Kabak": "Cucurbita pepo zucchini",
    "Kabak Çi̇çeği̇": "Cucurbita pepo squash blossom",
    "Kamkat": "Citrus japonica kumquat",
    "Karalahana": "Brassica oleracea acephala kale",
    "Karnabahar": "Brassica oleracea botrytis cauliflower",
    "Karpuz": "Citrullus lanatus watermelon",
    "Kavun": "Cucumis melo melon",
    "Kayisi": "Prunus armeniaca apricot",
    "Keki̇k (yaş-taze)": "Thymus vulgaris thyme",
    "Kerevi̇z": "Apium graveolens celeriac root",
    "Kerevi̇z Sap": "Starr 080531-4959 Apium graveolens",
    "Kirmizi Lahana": "OIC south perth red cabbage",
    "Ki̇raz": "Prunus avium cherry",
    "Ki̇ri̇ş (çi̇ri̇ş)": "Beta vulgaris chard greens",
    "Ki̇şni̇ş": "Coriandrum sativum coriander",
    "Ki̇vano": "Cucumis metuliferus kiwano",
    "Ki̇vi̇": "Actinidia deliciosa kiwifruit",
    "Kuzukulaği": "Rumex acetosa sorrel",
    "Li̇mon": "Citrus limon lemon",
    "Li̇mon Otu (li̇mon Grass)": "Cymbopogon citratus lemongrass stalks",
    "Mandali̇na": "Citrus reticulata mandarin",
    "Mandali̇na King": "Citrus reticulata clementine",
    "Mango": "Mangifera indica mango",
    "Mantar": "Agaricus bisporus mushroom",
    "Marul Göbekli̇": "Lactuca sativa romaine lettuce",
    "Marul Iceberg": "Lactuca sativa iceberg lettuce",
    "Marul Kivircik": "Lactuca sativa crispa lettuce",
    "Maydanoz": "Petroselinum crispum parsley",
    "Mersi̇n(yaban Mersi̇ni̇)": "Vaccinium myrtillus blueberry",
    "Misir taze": "Zea mays sweet corn",
    "Mi̇zuna Otu": "Brassica rapa mizuna",
    "Muz": "Musa banana",
    "Nane": "Mentha spicata mint",
    "Nar": "Punica granatum pomegranate",
    "Nektari̇n": "Prunus persica nectarine",
    "Nohut taze": "Cicer arietinum green chickpea pod",
    "Pakchoi̇": "Brassica rapa bok choy",
    "Pancar": "Beta vulgaris beetroot",
    "Patates": "Aardappel groene knollen Solanum tuberosum",
    "Patlican": "Solanum melongena eggplant",
    "Pazi": "Beta vulgaris swiss chard",
    "Pepi̇no": "Solanum muricatum pepino melon",
    "Pirasa": "Allium ampeloprasum leek",
    "Pi̇tahaya": "Pitaya cross section",
    "Pomelo": "Citrus maxima pomelo",
    "Portakal": "Citrus sinensis orange fruit",
    "Portakal Sikmalik": "Citrus sinensis juicing orange",
    "Portakal Washi̇ngton": "Citrus sinensis washington navel orange",
    "Rakula": "Eruca sativa arugula",
    "Rezene (yaş-taze)": "Foeniculum vulgare fennel",
    "Roka": "Eruca sativa arugula",
    "Salatalik": "Cucumis sativus cucumber",
    "Salatalik Turşuluk": "Cucumis sativus pickling cucumber",
    "Sarimsak kuru": "Allium sativum Garlic 01",
    "Sarimsak taze": "Allium sativum fresh garlic",
    "Semi̇zotu": "Portulaca oleracea purslane",
    "Soğan kuru": "Allium cepa onion",
    "Soya Fi̇li̇zi̇": "Soybean sprouts.jpg",
    "Şalgam": "File Brassica rapa turnip",
    "Şeftali̇": "Prunus persica peach",
    "Tamari̇llo": "Solanum betaceum tamarillo",
    "Tarhun": "Artemisia dracunculus tarragon",
    "Tatli Patates": "Ipomoea batatas sweet potato",
    "Tere": "Nasturtium officinale watercress",
    "Trabzon Hurmasi(cennet Elmasi)": "Diospyros kaki persimmon",
    "Turp": "Raphanus sativus radish",
    "Üzüm beyaz": "Bunch of grapes amidst vine leaves Ponte de Sor",
    "Üzüm Çeki̇rdeksi̇z": "Vitis vinifera sultana seedless grapes",
    "Vi̇şne": "Prunus cerasus sour cherry",
    "Yeni̇ Dünya(malta Eri̇ği̇)": "Eriobotrya japonica loquat",
    "Yeşi̇l Kabuklu Findik": "Corylus avellana green hazelnut",
    "Yeşi̇l Soğan": "Allium fistulosum scallion",
    "Yildiz Meyvesi̇": "Averrhoa carambola star fruit",
    "Zencefi̇l": "Zingiber officinale ginger root",
}